### ISSUE TITLE
The file is missing

### ISSUE THREAD

**Issue by 2654113847** [grandchicken/M2DF#1]
parser.add_argument('--image_text_region_similarity_path',
                        type=str,
                        default='/home/data_ti6_d/lich/CurriculumLearningMABSA/PreprocessData/similarity2015.json',
                        help='where to save the checkpoint')

    parser.add_argument('--object_nums_path',
                        type=str,
                        default= '/home/data_ti6_d/lich/CurriculumLearningMABSA/PreprocessData/object_nums2015.json',
                        help='where to save the checkpoint')
    In the code above，similarity2015.json and object_nums2015.json can not find the JSON files in the repository. Where do these two JSON files come from？ Thank you very much！

**Comment by 120L021411** [comment]
Actually,image_text_region_similarity_path is specified as src/data/jsons/amended_similarity_by_region2015.json in .sh files

**Comment by jiaweidoris** [comment]
I have the same problem. what is the JSON file:object_nums2015.json?

**Comment by 2654113847** [comment]
> In fact, object_nums2015.json is not needed in this code. I just deleted the code need to load it. I'm sorry for the inconvenience

Thank you very much！！Have a great life！！
