### ISSUE TITLE
实验结果

### ISSUE THREAD

**Issue by 2654113847** [grandchicken/M2DF#3]
您好！
我在cpu上进行twitter15数据的预训练时，发现我的实验结果总是为0。在前两轮迭代时，aesc_p和asec_r和aesc_f还有值，但是从第三轮后面，这几个值都变成0了。不知道您是否有类似问题的经历，打扰您了，期望您的回复！
eg：DEV  aesc_p:20.08 aesc_r:13.01 aesc_f:15.79
        DEV  aesc_p:0.0 aesc_r:0.0 aesc_f:0.0

**Comment by grandchicken** [comment]
这可能和cpu上的训练有关，你可以先试一下vlp-mabsa，也就是基模型在cpu上是否可以跑通，再来尝试我们的方法。我们一直使用cuda进行试验，没有遇到过这个问题

**Comment by 2654113847** [comment]
好的，谢谢您！
